name: dashboard
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:   
  - python==3.9.7
  - cartopy
  - bokeh<=2.2.2 # streamlit is buggy with new bokeh version
  - holoviews
  - geoviews
  - geopandas==0.9.0
  - pandas==1.3.3
  - numpy==1.21.3
  - matplotlib>=2.2.0
  - fiona==1.8.20
  - shapely==1.7.1
  - notebook==6.4.3
  - jupyterlab==3.1.7
  - pip==21.2.4
  - tqdm==4.62.2
  - streamlit
  - pip: 
    - wget==3.2
