name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:   
  - python==3.9.5
  - geopandas==0.9.0
  - pandas==1.2.5
  - numpy==1.21.0
  - matplotlib>=2.2.0
  - fiona==1.8.20
  - shapely==1.7.1
  - notebook==6.4.0
  - jupyterlab==3.0.16
  - pip==21.1.3
  - tqdm==4.62.2
  - pip: 
    - wget==3.2